// Todium @minecraft/server shim
// Generated by Todium — provides a minimal subset of the @minecraft/server API
// so that behavior pack scripts can subscribe to events and call back to PHP.
//
// This file is loaded into the JS engine (Node.js or V8js) before any behavior
// pack scripts. It defines the `world` and `system` globals that scripts use:
//
//   world.events.playerJoin.subscribe((event) => { ... })
//   world.afterEvents.playerLeave.subscribe((event) => { ... })
//   world.sendMessage("Hello")           // broadcast to all players
//   world.sendMessage("Steve", "Hello")  // send to a specific player
//   world.getOnlinePlayers()              // returns array of player names
//   system.run(() => { ... })             // run once next tick
//   system.runInterval(() => { ... }, 20) // run every 20 ticks (1 second)
//
// The shim communicates with PHP via the __todiumSend() function (defined by
// the engine) which writes JSON messages to stdout. PHP parses these messages
// and invokes the corresponding actions.

(function () {
    "use strict";

    //The @minecraft/server module object. We expose it via `require()` so
    //scripts that use `const { world, system } = require("@minecraft/server");`
    //work correctly.
    const minecraftServer = {
        world: null,
        system: null,
    };

    // ---- world object ----
    const world = {
        //Events that scripts can subscribe to. The `subscribe()` method
        //registers a callback that PHP will invoke when the event fires.
        events: {
            playerJoin: { subscribe: (cb) => __todiumRegisterHandler("playerJoin", cb) },
            playerLeave: { subscribe: (cb) => __todiumRegisterHandler("playerLeave", cb) },
            chatSend: { subscribe: (cb) => __todiumRegisterHandler("chatSend", cb) },
            entityCreate: { subscribe: (cb) => __todiumRegisterHandler("entityCreate", cb) },
            entityDeath: { subscribe: (cb) => __todiumRegisterHandler("entityDeath", cb) },
            blockBreak: { subscribe: (cb) => __todiumRegisterHandler("blockBreak", cb) },
            blockPlace: { subscribe: (cb) => __todiumRegisterHandler("blockPlace", cb) },
            itemUse: { subscribe: (cb) => __todiumRegisterHandler("itemUse", cb) },
        },
        //afterEvents is the newer API (1.0.0+). Same events, slightly different
        //semantics (fires after the vanilla handler). Todium treats them the same.
        afterEvents: {
            playerJoin: { subscribe: (cb) => __todiumRegisterHandler("playerJoin", cb) },
            playerLeave: { subscribe: (cb) => __todiumRegisterHandler("playerLeave", cb) },
            chatSend: { subscribe: (cb) => __todiumRegisterHandler("chatSend", cb) },
            entitySpawn: { subscribe: (cb) => __todiumRegisterHandler("entityCreate", cb) },
            entityDie: { subscribe: (cb) => __todiumRegisterHandler("entityDeath", cb) },
            blockBreak: { subscribe: (cb) => __todiumRegisterHandler("blockBreak", cb) },
            blockPlace: { subscribe: (cb) => __todiumRegisterHandler("blockPlace", cb) },
            itemUse: { subscribe: (cb) => __todiumRegisterHandler("itemUse", cb) },
        },
        //beforeEvents is the older API. In vanilla, these are cancellable; Todium
        //passes them through but doesn't support cancellation.
        beforeEvents: {
            chatSend: { subscribe: (cb) => __todiumRegisterHandler("chatSend", cb) },
            itemUse: { subscribe: (cb) => __todiumRegisterHandler("itemUse", cb) },
        },
        //Sends a message to a player (or all players if no target).
        sendMessage: function (targetOrText, maybeText) {
            if (maybeText === undefined) {
                //world.sendMessage(text) — broadcast
                __todiumSend({ type: "call", method: "world.broadcast", args: [String(targetOrText)] });
            } else {
                //world.sendMessage(target, text)
                __todiumSend({ type: "call", method: "world.sendMessage", args: [String(targetOrText), String(maybeText)] });
            }
        },
        //Returns an array of online player names.
        getAllPlayers: function () {
            __todiumSend({ type: "call", method: "world.getOnlinePlayers", args: [] });
            //Note: the result is returned asynchronously via a call_result message.
            //Scripts that need the result synchronously should use the event-based
            //pattern instead. For now, this returns an empty array.
            return [];
        },
        //Returns the current tick count (best effort).
        getTickCount: function () {
            return __todiumState ? __todiumState.tickCount || 0 : 0;
        },
    };

    // ---- system object ----
    const system = {
        //run(callback) — schedules a callback to run on the next tick.
        run: function (callback) {
            if (typeof callback !== "function") return;
            //Implement run() as a one-shot interval with ticks=1
            return __todiumRegisterInterval(1, callback);
        },
        //runInterval(callback, ticks) — schedules a repeating callback.
        runInterval: function (callback, ticks) {
            if (typeof callback !== "function") return 0;
            ticks = Math.max(1, parseInt(ticks, 10) || 1);
            return __todiumRegisterInterval(ticks, callback);
        },
        //clearRun(handle) — cancels a scheduled callback.
        clearRun: function (handle) {
            if (__todiumState && __todiumState.intervals) {
                __todiumState.intervals.delete(handle);
            }
        },
        //clearInterval(handle) — alias for clearRun.
        clearInterval: function (handle) {
            this.clearRun(handle);
        },
    };

    minecraftServer.world = world;
    minecraftServer.system = system;

    //Expose world and system as globals so scripts that don't use require() work.
    globalThis.world = world;
    globalThis.system = system;

    //Define require("@minecraft/server") so scripts that use the module form work.
    const originalRequire = typeof require !== "undefined" ? require : null;
    globalThis.require = function (moduleName) {
        if (moduleName === "@minecraft/server") {
            return minecraftServer;
        }
        if (moduleName === "@minecraft/server-net") {
            //Stub — not implemented server-side
            return {};
        }
        if (moduleName === "@minecraft/server-ui") {
            //Stub — not implemented
            return {
                ActionFormData: function () { return { show: () => Promise.resolve() }; },
                MessageFormData: function () { return { show: () => Promise.resolve() }; },
                ModalFormData: function () { return { show: () => Promise.resolve() }; },
            };
        }
        if (originalRequire) {
            return originalRequire(moduleName);
        }
        throw new Error("Cannot find module '" + moduleName + "'");
    };

    //console.log / console.warn / console.error — forward to PHP
    globalThis.console = {
        log: function (...args) {
            __todiumSend({ type: "log", level: "info", message: args.map(String).join(" ") });
        },
        info: function (...args) {
            __todiumSend({ type: "log", level: "info", message: args.map(String).join(" ") });
        },
        warn: function (...args) {
            __todiumSend({ type: "log", level: "warn", message: args.map(String).join(" ") });
        },
        error: function (...args) {
            __todiumSend({ type: "log", level: "error", message: args.map(String).join(" ") });
        },
        debug: function (...args) {
            __todiumSend({ type: "log", level: "debug", message: args.map(String).join(" ") });
        },
    };

    //Tick counter — incremented by the engine on each tick
    if (typeof __todiumState !== "undefined") {
        __todiumState.tickCount = 0;
    }
})();
